/*
& Cada cliente deverá ter um nome, um telefone, um limite de crédito, e um país;
& Um país deverá ter nome e sigla;
& Não é permitido mais de um cliente com o mesmo nome;
& Não é permitido mais de um país com o mesmo nome;
& O telefone precisa ser validado de acordo com o país;
O limite de crédito é dado automaticamente de acordo com a idade: Para clientes até 18 anos o limite é R$ 100,00. Entre 18 e 35 é R$ 300,00. Acima de 35 é R$ 500,00;
Se o cliente morar no Brasil, ele terá um crédito adicional de R$ 100,00, independente da idade;
& Cada país deverá ser identificado pelo nome e abreviação;
& O nome do cliente não pode ser menor que 5 caracteres, e o campo país não pode ser nulo/vazio;
& Deve ser possível incluir um país antes, durante ou depois de criar um cliente;
& Os dados devem ser armazenados em memória RAM por meio de estruturas de dados (arrays, listas, conjuntos);
& Deve haver uma interface gráfica para interação com usuário (GUI)
 */
package View;

import Bean.Cliente;
import Bean.Pais;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Tamires
 */
public class Principal extends javax.swing.JFrame {

    List<Pais> listaPais = new ArrayList<>();
    List<Cliente> listaNomes = new ArrayList<>();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        botaoCancelaPais.doClick();// aparece escondido
        btnCancelarNome.doClick();
    }

    void populaListas() {
        //ComboBoxPais.removeAll();
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel();
        for (Pais percorrer : listaPais) {
            comboModel.addElement(percorrer.getNome());
        }
        ComboBoxPais.setModel(comboModel);
        ComboBoxPais.addItem("Teste");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JLnomes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLPais = new javax.swing.JList<>();
        btnNovaPessoa = new javax.swing.JButton();
        btnNovoPais = new javax.swing.JButton();
        PainelNovoPais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoCancelaPais = new javax.swing.JButton();
        campoNovoPais = new javax.swing.JTextField();
        campoSigla = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bontaoSalvaPais = new javax.swing.JButton();
        cmpDDIPais = new javax.swing.JTextField();
        PainelNovaPessoa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        cmpDDINome = new javax.swing.JTextField();
        cmpTel = new javax.swing.JTextField();
        cmpIdade = new javax.swing.JTextField();
        cmpLimCred = new javax.swing.JTextField();
        btnSalvarNome = new javax.swing.JButton();
        btnCancelarNome = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ComboBoxPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(JLnomes);

        jLabel1.setText("Nomes");

        jLabel2.setText("Paises");

        jScrollPane2.setViewportView(jLPais);

        btnNovaPessoa.setText("Nova Pessoa");
        btnNovaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPessoaActionPerformed(evt);
            }
        });

        btnNovoPais.setText("Novo Pais");
        btnNovoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPaisActionPerformed(evt);
            }
        });

        jLabel3.setText("Novo Pais");

        jLabel4.setText("Nome");

        jLabel5.setText("Sigla");

        botaoCancelaPais.setText("Cancelar");
        botaoCancelaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelaPaisActionPerformed(evt);
            }
        });

        campoNovoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNovoPaisActionPerformed(evt);
            }
        });

        jLabel12.setText("DDI");

        bontaoSalvaPais.setText("Salvar");
        bontaoSalvaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bontaoSalvaPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelNovoPaisLayout = new javax.swing.GroupLayout(PainelNovoPais);
        PainelNovoPais.setLayout(PainelNovoPaisLayout);
        PainelNovoPaisLayout.setHorizontalGroup(
            PainelNovoPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovoPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelNovoPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelNovoPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PainelNovoPaisLayout.createSequentialGroup()
                            .addComponent(bontaoSalvaPais)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoCancelaPais))
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(campoSigla)
                        .addComponent(campoNovoPais))
                    .addComponent(jLabel12)
                    .addComponent(cmpDDIPais, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelNovoPaisLayout.setVerticalGroup(
            PainelNovoPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovoPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNovoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmpDDIPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovoPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bontaoSalvaPais)
                    .addComponent(botaoCancelaPais)))
        );

        jLabel6.setText("Nova Pessoa");

        jLabel7.setText("Nome:");

        jLabel8.setText("Telefone:");

        jLabel9.setText("Idade:");

        jLabel10.setText("Lim. de Crédito:");

        cmpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNomeActionPerformed(evt);
            }
        });

        cmpDDINome.setEnabled(false);

        cmpLimCred.setEnabled(false);

        btnSalvarNome.setText("Salvar");
        btnSalvarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNomeActionPerformed(evt);
            }
        });

        btnCancelarNome.setText("Cancelar");
        btnCancelarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNomeActionPerformed(evt);
            }
        });

        jLabel11.setText("Pais:");

        ComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - -" }));
        ComboBoxPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxPaisItemStateChanged(evt);
            }
        });
        ComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelNovaPessoaLayout = new javax.swing.GroupLayout(PainelNovaPessoa);
        PainelNovaPessoa.setLayout(PainelNovaPessoaLayout);
        PainelNovaPessoaLayout.setHorizontalGroup(
            PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpNome))
                    .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpDDINome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpTel))
                    .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmpIdade))
                    .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmpLimCred))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelNovaPessoaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarNome)
                        .addGap(28, 28, 28))
                    .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PainelNovaPessoaLayout.setVerticalGroup(
            PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNovaPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmpDDINome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmpIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmpLimCred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(ComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelNovaPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarNome)
                    .addComponent(btnCancelarNome))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovoPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNovaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelNovaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(PainelNovoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovaPessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnNovoPais)
                        .addGap(24, 24, 24))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelNovoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PainelNovaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPessoaActionPerformed
        PainelNovaPessoa.setVisible(true);
    }//GEN-LAST:event_btnNovaPessoaActionPerformed

    private void btnNovoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPaisActionPerformed
        PainelNovoPais.setVisible(true);
    }//GEN-LAST:event_btnNovoPaisActionPerformed

    private void bontaoSalvaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bontaoSalvaPaisActionPerformed
        String campPais = campoNovoPais.getText();//getText pegar a informação que usuario digitou
        String campSigla = campoSigla.getText();
        int ddi = Integer.parseInt(cmpDDIPais.getText());

        Pais pais = new Pais();
        pais.setNome(campPais);
        pais.setSigla(campSigla);
        pais.setDdi(ddi);

        boolean naoExiste = true;
        for (int i = 0; i < listaPais.size(); i++) {
            if (pais.getNome().toLowerCase().equals(listaPais.get(i).getNome().toLowerCase())) {
                JOptionPane.showMessageDialog(null, "Pais já cadastrado");
                naoExiste = false;
            }
        }
        if (naoExiste) {
            listaPais.add(pais);
            jLPais.removeAll();
            DefaultListModel listModel = new DefaultListModel();
            for (Pais percorrer : listaPais) {
                listModel.addElement(percorrer.getNome());
            }
            jLPais.setModel(listModel);
            ComboBoxPais.addItem(campPais);
            LimpaCamposPais();
        } else {
            botaoCancelaPais.doClick();
        }
    }//GEN-LAST:event_bontaoSalvaPaisActionPerformed

    private void botaoCancelaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelaPaisActionPerformed
        LimpaCamposPais();
        PainelNovoPais.setVisible(false);
    }//GEN-LAST:event_botaoCancelaPaisActionPerformed

    private void cmpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNomeActionPerformed

    private void campoNovoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNovoPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNovoPaisActionPerformed

    private void btnCancelarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNomeActionPerformed
        limparCampoNome();
        PainelNovaPessoa.setVisible(false);

    }//GEN-LAST:event_btnCancelarNomeActionPerformed

    private void btnSalvarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNomeActionPerformed
        Cliente cliente = new Cliente();
        int k = ComboBoxPais.getSelectedIndex();
        
        cliente.setNome(cmpNome.getText());
        
        cliente.setTelefone(cmpDDINome.getText() + cmpTel.getText());
        
        int idade =Integer.parseInt(cmpIdade.getText());
        cliente.setIdade(idade);
        
        float limite = LimiteCredito(idade,listaPais.get(k-1).getNome());
        cliente.setLimiteDeCredito(limite);
        
        cliente.setPais(listaPais.get(k-1));
        
        
        boolean naoExiste = true;
        for (int i = 0; i < listaNomes.size(); i++) {
            if (cliente.getNome().toLowerCase().equals(listaNomes.get(i).getNome().toLowerCase())) {
                JOptionPane.showMessageDialog(null, "Nome já cadastrado");
                naoExiste = false;
            }
        }
        if (naoExiste) {
            ValidarUsuario(cliente);
            listaNomes.add(cliente);
            JLnomes.removeAll(); // REMOVER TUDO QUE TEM NA LISTA
            DefaultListModel listModel = new DefaultListModel();
            for (Cliente percorrer : listaNomes) {
                listModel.addElement(percorrer.getNome());
            }
            JLnomes.setModel(listModel);
            limparCampoNome();
        } else {
            btnCancelarNome.doClick();
        }


    }//GEN-LAST:event_btnSalvarNomeActionPerformed

    private void ComboBoxPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxPaisItemStateChanged
        
    }//GEN-LAST:event_ComboBoxPaisItemStateChanged

    private void ComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPaisActionPerformed
        // TODO add your handling code here:
       int i = ComboBoxPais.getSelectedIndex();
        int idade =Integer.parseInt(cmpIdade.getText());
        System.out.println("I: " + i + " lista: " + listaPais.get(i-1).getDdi());
        cmpDDINome.setText("+" + listaPais.get(i-1).getDdi());
        cmpLimCred.setText("R$"+ LimiteCredito(idade,listaPais.get(i-1).getNome())); 
    }//GEN-LAST:event_ComboBoxPaisActionPerformed
    void limparCampoNome() {
        cmpNome.setText("");
        cmpIdade.setText("");
        cmpDDINome.setText("");
        cmpLimCred.setText("");
        cmpTel.setText("");
       
    }
    private float LimiteCredito(int idade, String pais){
        float limite =0;
        
        if(idade <=18){
            limite = 100;
        }else if(idade > 18 && idade <= 35){
            limite = 300;
        }else if(idade > 35){
            limite =500;
        }
        
        if(pais.toLowerCase().equals("brasil")){
            limite = limite + 100;
        }
        return limite;
    }
    private void LimpaCamposPais() {
        campoNovoPais.setText("");
        campoSigla.setText("");
        cmpDDIPais.setText("");
        
    }

    void ValidarUsuario(Cliente cliente) {
        if (cliente.getNome().length() < 5) {
            JOptionPane.showMessageDialog(null, "Nome incorreto, digite um nome com mais de 5 caracteres");
        }

        
        if (cliente.getPais().getNome().equals("") || cliente.getPais() == (null)) {
            JOptionPane.showMessageDialog(null, "Nome Incorreto");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPais;
    private javax.swing.JList<String> JLnomes;
    private javax.swing.JPanel PainelNovaPessoa;
    private javax.swing.JPanel PainelNovoPais;
    private javax.swing.JButton bontaoSalvaPais;
    private javax.swing.JButton botaoCancelaPais;
    private javax.swing.JButton btnCancelarNome;
    private javax.swing.JButton btnNovaPessoa;
    private javax.swing.JButton btnNovoPais;
    private javax.swing.JButton btnSalvarNome;
    private javax.swing.JTextField campoNovoPais;
    private javax.swing.JTextField campoSigla;
    private javax.swing.JTextField cmpDDINome;
    private javax.swing.JTextField cmpDDIPais;
    private javax.swing.JTextField cmpIdade;
    private javax.swing.JTextField cmpLimCred;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpTel;
    private javax.swing.JList<String> jLPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
